### PR TITLE
Data853_upgrading_snowflake_sdk_version

### PR DESCRIPTION
**Pull request by lokeshgurjar**
Data853_upgrading_snowflake_sdk_version. Updated snowflake-sdk version to v1.4.0 and same is tested in local.

### CODE REVIEW

**Comment by lokeshgurjar** [comment]
@AnkitVBarsainya Please review this PR.

**Review by AnkitVBarsainya — COMMENTED** [review]
LGTM. @rajpalparyani Please review at your end.

**Review by rajpalparyani — APPROVED** [review]
LGTM

**Comment by rajpalparyani** [comment]
hey @lokeshgurjar  - I merged the changes to master and also published the latest version to npm https://www.npmjs.com/package/empujar/v/0.2.15 .. Please use this version in tr_empujar, test it in staging and then send that PR to us.

**Pull request merged**
